spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/request_bin?createDatabaseIfNotExist=true
    username: root
  data:
    cassandra:
      contact-points: localhost
request-bin:
  maxFetchSize: 100
  adminSecret: ca5218c5-76a1-4d78-aedb-f3714abb151b
  binExpiryDuration: PT1H
  persistentBins:
    - demo