spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/request_bin?createDatabaseIfNotExist=true
    username: root
  data:
    cassandra:
      contact-points: localhost
request-bin:
  maxFetchSize: 100
  binExpiryDuration: PT168H
  persistentBins:
    - DEMO