spring:
  application:
    name: request-bin-server
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
  datasource:
    url: jdbc:mysql://localhost:3306/request_bin?createDatabaseIfNotExist=true
    username: root

server:
  port: 8080