logging:
  level:
    io.graversen: debug
server:
  port: 8080
spring:
  application:
    name: request-bin-server
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    active: dev
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.data.cassandra.CassandraReactiveDataAutoConfiguration