version: "3.7"
services:
  cassandra:
    container_name: request-bin-cassandra
    image: cassandra:3.11.11
    restart: unless-stopped
    volumes:
      - cassandra-volume:/var/lib/cassandra

  mysql:
    container_name: request-bin-mysql
    image: bitnami/mysql:8.0.23
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql-volume:/bitnami/mysql/data

  request-bin-server:
    container_name: request-bin-server
    image: request-bin/request-bin-server
    restart: unless-stopped
    build:
      context: ../server
      dockerfile: Docker/Dockerfile
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://request-bin-mysql:3306/request_bin?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATA_CASSANDRA_CONTACT-POINTS: request-bin-cassandra
      SPRING_PROFILES_ACTIVE: prod
    env_file:
      - request-bin-server.env

  request-bin-client:
    container_name: request-bin-client
    image: request-bin/request-bin-client
    restart: unless-stopped
    build:
      context: ../client
      dockerfile: Docker/Dockerfile
    networks:
      - graversen-io-network

networks:
  graversen-io-network:
    driver: bridge

volumes:
  mysql-volume:
  cassandra-volume: