version: "3.7"
services:
  cassandra:
    container_name: request-bin-cassandra
    image: cassandra:3.11.0
    volumes:
      - cassandra-volume
  mysql:
    container_name: request-bin-mysql
    image: mysql:8.0.17
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mysql-volume
  request-bin-server:
      container_name: request-bin-server
      image: request-bin/request-bin-server
      restart: on-failure
      depends_on:
        - mysql
        - cassandra
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://request-bin-mysql:3306/request_bin?createDatabaseIfNotExist=true
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATA_CASSANDRA_CONTACT-POINTS: request-bin-cassandra
  request-bin-client:
    container_name: request-bin-client
    image: request-bin/request-bin-client
    ports: 
      - 10021:80